name: user-authentication

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout my repo
        uses: actions/checkout@v3

      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('require-tests.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        working-directory: tests/
        run: |
          pip install --upgrade pip
          pip install -r require-tests.txt

      - name: End 2 End test
        working-directory: tests/
        run: python -m pytest test_main.py -s -v 

